---
name: R-hub

on:
  push:
    branches:
      - custom
  workflow_dispatch:

jobs:
  rhub:
    name: R-hub
    uses: insightsengineering/r.pkg.template/.github/workflows/rhub.yaml@test-rhub-workflows
    with:
      lookup-refs: |
        averissimo/pkg1
        averissimo/pkg3
        averissimo/pkg4
